fix: upgrade xalan to 2.7.3 and add explicit ref to serializer
The explicit ref seems to be needed to avoid error
java.lang.NoClassDefFoundError: org/apache/xml/serializer/OutputPropertiesFactory